---

- hosts: all
  vars_prompt:
    - name: webhook
      prompt: Enter the webhook
  tasks:
  - name: Install Docker Dependencies
    apt: name={{ item }} state=latest update_cache=yes
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common 
      - gpg
    tags: docker

  - name: Get Docker key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    tags: docker

  - name: Add Docker packages to Repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_lsb.codename|lower }} stable
    tags: docker

  - name: Install Docker-CE
    apt: name="docker-ce" state=latest update_cache=yes
    tags: docker

  - name: Install docker-compose
    apt: name="docker-compose" state=latest
    tags: docker

  # this could also just copy files from current folder (on local machine) to /opt/status (remote machine)
  - name: Git checkout
    ansible.builtin.git:
      repo: 'https://github.com/testausserveri/status.git'
      dest: /opt/status
      version: master
      force: yes

  - name: Ensure webhook is set (testausserveri)
    ansible.builtin.lineinfile:
      path: /opt/status/config/testausserveri/config.yaml
      regexp: '^(.*)WEBHOOK_PLACEHOLDER(.*)$'
      line: "    webhook-url: \"{{ webhook }}\""
      backrefs: yes

  - name: Ensure webhook is set (members)
    ansible.builtin.lineinfile:
      path: /opt/status/config/members/config.yaml
      regexp: '^(.*)WEBHOOK_PLACEHOLDER(.*)$'
      line: "    webhook-url: \"{{ webhook }}\""
      backrefs: yes

  - name: Start the status page
    community.docker.docker_compose:
      project_src: /opt/status