storage:
  type: postgres
  path: "postgres://username:password@testausserveripostgres:5432/gatus?sslmode=disable"

debug: true
skip-invalid-config-update: true
disable-monitoring-lock: true

alerting:
  discord:
    webhook-url: "WEBHOOK_PLACEHOLDER"
    default-alert:
      enabled: true
      send-on-resolved: true
      failure-threshold: 2
      success-threshold: 2

ui:
  title: Testausserveri - Status
  header: Testausserveri - Status
  description: Testausserveri-organisaation palveluiden tilannehuone.
  logo: https://static.testausserveri.fi/testausserveri_logo_colored_square.png # https://testausserveri.fi/logo.svg
  ui.link: https://testausserveri.fi
  buttons:
    - name: Jäsenten sivujen status
      link: https://members.status.testausserveri.fi

endpoints:
  - name: Etusivu
    group: 01 - Viralliset
    url: "https://testausserveri.fi/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
      # - "[DOMAIN_EXPIRATION] > 720h"
    alerts:
      - type: discord

  - name: API
    group: 01 - Viralliset
    url: "https://api.testausserveri.fi/v1/discord/guildInfo"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "has([BODY].codingLeaderboard) == true"
      - "has([BODY].messagesLeaderboard) == true"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: discord

  - name: Karhu
    group: 01 - Viralliset
    url: "https://karhu.testausserveri.fi/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: discord

  - name: OpenWilma
    group: 01 - Viralliset
    url: "https://openwilma.testausserveri.fi/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: discord

  - name: QR-pyörä
    group: 01 - Viralliset
    url: "https://qrpyora.fi/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
      # - "[DOMAIN_EXPIRATION] > 720h"
    alerts:
      - type: discord

  - name: Bitwarden
    group: 01 - Viralliset
    url: "https://bitwarden.testausserveri.fi/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: discord

  - name: Testausserveri ID
    group: 01 - Viralliset
    url: "https://id.testausserveri.fi/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: discord

  - name: Mastodon
    group: 01 - Viralliset
    url: "https://mastodon.testausserveri.fi/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: discord

  # For some reason this does not currently work
  # - name: Koirameili
  #   group: 01 - Viralliset
  #   url: "tcp://152.67.70.55:25"
  #   interval: 1m
  #   conditions:
  #     - "[CONNECTED] == true"
  #   alerts:
  #     - type: discord

  - name: Kaatis.party
    group: 01 - Viralliset
    url: "https://kaatis.party/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: discord

  - name: Etusivu
    group: 02 - Testaustime
    url: "https://testaustime.fi/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
      # - "[DOMAIN_EXPIRATION] > 720h"
    alerts:
      - type: discord

  - name: API
    group: 02 - Testaustime
    url: "https://api.testaustime.fi/health"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: discord

  - name: Matikkaeditori
    group: 03 - Matikkaeditori
    url: "https://matikkaeditori.fi/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
      # - "[DOMAIN_EXPIRATION] > 720h"
    alerts:
      - type: discord

  - name: v3
    group: 03 - Matikkaeditori
    url: "https://v3.matikkaeditori.fi/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: discord

  - name: Beta
    group: 03 - Matikkaeditori
    url: "https://beta.matikkaeditori.fi/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: discord
      
  - name: Kaava
    group: 03 - Matikkaeditori
    url: "https://kaava.matikkaeditori.fi/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
    alerts:
      - type: discord

  - name: Abitikku
    group: 04 - Abitikku
    url: "https://abitikku.fi/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
      # - "[DOMAIN_EXPIRATION] > 720h"
    alerts:
      - type: discord

  - name: testaus.link
    group: 05 - testaus.link
    url: "https://testaus.link/"
    interval: 1m
    conditions:
      - "[STATUS] == 200"
      - "[CERTIFICATE_EXPIRATION] > 48h"
      # - "[DOMAIN_EXPIRATION] > 720h"
    alerts:
      - type: discord

  - name: Teapot
    group: 06 - Palvelimet
    url: "https://teapot.testausserveri.fi"
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
      - "[IP] == 152.67.70.55"
    alerts:
      - type: discord
