name: Copy updated config
on: [push]

jobs:
  Copy-Config:
    name: Copy configuration to the server
    runs-on: ubuntu-latest
    steps:
    - name: Remove all folders in /opt/gatus
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          sudo rm -rf /opt/docker-services
          sudo mkdir /opt/docker-services
          # We need perms for SCP transfer for exactly THIS user (that has SSH access)
          sudo chown $(whoami): /opt/docker-services
    - uses: actions/checkout@master
    - name: copy files from opt-dir to servers opt dir
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "gatus/"
        target: "/opt/docker-services/"
    - name: Add secret webhooks
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /opt/docker-services/gatus
          sed -i -e "s/##WEBHOOK_PLACEHOLDER##/${{ secrets.WEBHOOK_URL }}/g" /opt/docker-services/gatus/config/*
    - name: Run docker-compose
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /opt/docker-services/gatus
          sudo docker-compose up -d --remove-orphans
